"""user ip allowlist

Revision ID: 96c715b5c6a6
Revises: 30da70cd4eba
Create Date: 2026-03-08 10:26:40.188606

"""
from alembic import op
import sqlalchemy as sa


revision = "96c715b5c6a6"
down_revision = '30da70cd4eba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_ip_allowlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ip_or_network', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ip_or_network', name='uq_user_ip_allowlist_user_ip')
    )
    op.create_index(op.f('ix_user_ip_allowlist_id'), 'user_ip_allowlist', ['id'], unique=False)
    op.create_index(op.f('ix_user_ip_allowlist_user_id'), 'user_ip_allowlist', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_ip_allowlist_user_id'), table_name='user_ip_allowlist')
    op.drop_index(op.f('ix_user_ip_allowlist_id'), table_name='user_ip_allowlist')
    op.drop_table('user_ip_allowlist')
    # ### end Alembic commands ###
